"""add image_url to cars

Revision ID: 7f98702c7a83
Revises: e6379230564c
Create Date: 2025-05-30 14:53:12.444453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f98702c7a83'
down_revision: Union[str, None] = 'e6379230564c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cars', 'foto_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('foto_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('cars', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
