"""adicionar campo senha ao modelo User

Revision ID: 97668b1bb9e4
Revises: ac3940a9fa19
Create Date: 2025-04-27 23:01:36.601554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97668b1bb9e4'
down_revision: Union[str, None] = 'ac3940a9fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###
